=begin
#EVE Swagger Interface

#An OpenAPI for EVE Online

OpenAPI spec version: 0.4.5

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Esi::ContactLabel
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ContactLabel' do
  before do
    # run before each test
    @instance = Esi::ContactLabel.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ContactLabel' do
    it 'should create an instact of ContactLabel' do
      expect(@instance).to be_instance_of(Esi::ContactLabel)
    end
  end
  describe 'test attribute "label_id"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "label_name"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

