=begin
#EVE Swagger Interface

#An OpenAPI for EVE Online

OpenAPI spec version: 0.4.4

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::GetKillmailsKillmailIdKillmailHashItem
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'GetKillmailsKillmailIdKillmailHashItem' do
  before do
    # run before each test
    @instance = SwaggerClient::GetKillmailsKillmailIdKillmailHashItem.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GetKillmailsKillmailIdKillmailHashItem' do
    it 'should create an instact of GetKillmailsKillmailIdKillmailHashItem' do
      expect(@instance).to be_instance_of(SwaggerClient::GetKillmailsKillmailIdKillmailHashItem)
    end
  end
  describe 'test attribute "flag"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "item_type_id"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "quantity_destroyed"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "quantity_dropped"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "singleton"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

