=begin
#EVE Swagger Interface

#An OpenAPI for EVE Online

OpenAPI spec version: 0.4.4

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::PutCharactersCharacterIdCalendarEventIdResponse
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PutCharactersCharacterIdCalendarEventIdResponse' do
  before do
    # run before each test
    @instance = SwaggerClient::PutCharactersCharacterIdCalendarEventIdResponse.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PutCharactersCharacterIdCalendarEventIdResponse' do
    it 'should create an instact of PutCharactersCharacterIdCalendarEventIdResponse' do
      expect(@instance).to be_instance_of(SwaggerClient::PutCharactersCharacterIdCalendarEventIdResponse)
    end
  end
  describe 'test attribute "response"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
       #validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["accepted", "declined", "tentative"])
       #validator.allowable_values.each do |value|
       #  expect { @instance.response = value }.not_to raise_error
       #end
    end
  end

end

